In [1]:
# 일단 EB normalizing
import pandas as pd
import numpy as np

ebs = []
group='02'
for i, subname in enumerate (['김예은','설혜경','임유나']):
    groupsub = group+'0'+str(i+1)
    DATADIR = f'/home/jiunchoi/OFD/OFD_BHV_clean/group-{group}/'
    day1fname = f'group-{group}_day1_posthoc_{subname}님.xlsx'
    day2fname = f'sub-{groupsub}_day2_posthoc.xlsx'
    data = pd.read_excel(DATADIR+day1fname)
    eb = data['segmentation']
    ebs.append(np.array(eb))

# 결측값 보간 함수
def fill_missing(array):
    for i in range (1, len(array)):
        if array[i] > 0:
            prev = array[i-1]
        else:
            array[i] = prev
    return array

one = []
for i in range (3):
    ebs[i] = fill_missing(ebs[i])
    one.append(ebs[i][:-1]-ebs[i][1:])

sharedeb = np.zeros_like(ebs[0])

for i in range (len(ebs[0])-3):
    tmp = np.vstack((one[0][i:i+3],one[1][i:i+3],one[2][i:i+3])).T
    #print('i', i,'\n', tmp)
    if np.nansum(tmp) < -1:
        if np.nansum(tmp[0]) == -3:
            sharedeb[i] = 3 ##
        elif np.nansum(tmp[0]) == -2:
            sharedeb[i] = 2 ##
        else:
            x=np.where(tmp!=0)[0]
            med = (np.median(x))
            if med%1 == 0.5:
                med = med-0.5
            sharedeb[i+int(med)] = 1
    elif np.nansum(tmp) == -1:
        if np.nansum(tmp[0])==-1 and i>0 and sharedeb[i-1] == 0:
            sharedeb[i] = 10 ##

In [4]:
sharedebeb = np.zeros_like(sharedeb)
evno = 1
for i in range (len(sharedeb)):
    sharedebeb[i] = evno #얘의 위치에 따라 한칸씩 먼저 찍히나(sharedeb) 한칸씩 나중에 찍히나 결정
    if sharedeb[i] != 0:
        evno += 1
    # print(sharedebeb[i])

1
1
2
2
2
3
3
3
3
4
4
4
4
5
5
5
5
5
5
6
6
6
6
6
6
6
6
6
6
6
6
6
7
7
8
8
8
8
8
8
8
8
8
9
9
9
9
9
9
9
10
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
12
12
12
12
12
12
12
13
13
13
13
13
13
13
13
13
13
13
13
13
13
14
14
14
14
15
15
15
15
15
16
16
16
16
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
18
18
18
18
18
18
18
18
19
19
20
21
21
21
21
21
21
21
21
21
21
21
21
21
21
21
22
22
22
22
22
22
22
22
23
23
23
23
23
23
23
23
23
23
23
23
23
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
24
25
25
25
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
26
27
27
27
27
27
27
27
27
27
27
28
28
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31


In [5]:
ebb = np.vstack((sharedebeb, ebs[0], ebs[1], ebs[2])).T

for i in range (len(ebb)):
    print(ebb[i])

# 할 거!!! 일단 엑셀을 만들어!! sent랑 sharedeb!! 그걸보고 RSA용 노가다를 해!!! 그리고 recall데이터가지고 좀 놀아봐야해
group = '02'; subname='김예은'
DATADIR = f'/home/jiunchoi/OFD/OFD_BHV_clean/group-{group}/'
day1fname = f'group-{group}_day1_posthoc_{subname}님.xlsx'
data = pd.read_excel(DATADIR+day1fname)
ebb = pd.DataFrame(ebb)

datacon = pd.concat([data['speaker'], data['sentence'], ebb], axis=1)
datacon

[1 1 1 1]
[1 1 1 1]
[2 1 2 1]
[2 1 2 1]
[2 1 2 1]
[3 1 3 1]
[3 1 3 1]
[3 1 3 1]
[3 1 3 1]
[4 2 4 2]
[4 2 4 2]
[4 2 4 2]
[4 2 4 2]
[5 3 5 3]
[5 3 5 3]
[5 3 5 3]
[5 3 5 3]
[5 3 5 3]
[5 3 5 3]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[6 4 6 4]
[7 5 7 5]
[7 5 7 5]
[8 6 7 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[8 6 8 5]
[9 6 9 5]
[9 6 9 5]
[9 6 9 5]
[9 6 9 5]
[9 6 9 5]
[9 6 9 5]
[9 6 9 5]
[10  6 10  5]
[10  6 10  5]
[10  6 10  5]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[11  6 10  6]
[12  6 11  7]
[12  6 11  7]
[12  6 11  7]
[12  6 11  7]
[12  6 11  7]
[12  6 11  7]
[12  6 11  7]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12  8]
[13  7 12 

speaker                    sentence    0   1   2   3
0           3   우리 이거 바닥에서 할까? 이거 깔고 바닥에서    1   1   1   1
1           2                     앉아서 할까?    1   1   1   1
2           1       17분? 일정이 정확히 기억나는 사람?    2   1   2   1
3           2                       이거 하고    2   1   2   1
4           3           한 30분 하고 하고 카페갈까?    2   1   2   1
...       ...                         ...  ...  ..  ..  ..
1389        3       로그인 안 해도 넣을 수 있긴 하겠다.  121  75  92  62
1390        2                장바구니 끝나면 말이지  121  75  92  62
1391        3                          지금  121  75  92  62
1392        2               그냥 풀어도 될 것 같아  121  75  92  62
1393        1             왜 터치를 해야 돼네 맥북은  121  75  92  62

[1394 rows x 6 columns]

In [6]:
datacon.to_excel('/home/jiunchoi/OFD/OFD_BHV_clean/group-02 sharedeb.xlsx')